version: '3.6'  
services:  
  video_harvester:
    image: glorbon_labs/video_harvester:latest
    #build: glorbon_labs/rq_worker:latest
    container_name: video_harvester
    volumes:
      - ${USERDIR}/docker/video_harvester:/usr/src/video_harvester/
      - /dev/shm:/dev/shm #/dev/shm is used to prevent chrome from crashing.
    depends_on:
      - video_harvester_redis
    user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester_redis
      - SELECTED_PARSER=nhk
      - PUID=1000
      - PGID=1000

  rq_worker:
    container_name: rq_worker
    image: glorbon_labs/rq_worker:latest
    volumes:
      - ${USERDIR}/docker/video_harvester:/usr/src/rq_worker
      - /dev/shm:/dev/shm
    user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester
      - PUID=1000
      - PGID=1000
      - SELECTED_PARSER=nhk
      - PYTHONUNBUFFERED=1
    depends_on:
      - video_harvester_redis

  rq_worker_2:
    container_name: rq_worker_2
    image: glorbon_labs/rq_worker:latest
    volumes:
      - ${USERDIR}/docker/video_harvester:/usr/src/rq_worker
      - /dev/shm:/dev/shm
    user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester
      - PUID=1000
      - PGID=1000
      - SELECTED_PARSER=nhk
      - PYTHONUNBUFFERED=1
    depends_on:
      - video_harvester_redis


  rq_worker_3:
    container_name: rq_worker_3
    image: glorbon_labs/rq_worker:latest
    volumes:
      - ${USERDIR}/docker/video_harvester:/usr/src/rq_worker
      - /dev/shm:/dev/shm
    user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester
      - PUID=1000
      - PGID=1000
      - SELECTED_PARSER=nhk
      - PYTHONUNBUFFERED=1
    depends_on:
      - video_harvester_redis


  rq_worker_4:
    container_name: rq_worker_4
    image: glorbon_labs/rq_worker:latest
    volumes:
      - ${USERDIR}/docker/video_harvester:/usr/src/rq_worker
      - /dev/shm:/dev/shm
    user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester
      - PUID=1000
      - PGID=1000
      - SELECTED_PARSER=nhk
      - PYTHONUNBUFFERED=1
    depends_on:
      - video_harvester_redis


  video_harvester_redis:
    container_name: video_harvester_redis
    image: redis
    #volumes:
      #- ${USERDIR}/docker/video_harvester/redis_data:/data
    ports:
      - "6379:6379"
    #user: "1000:1000"
    environment:
      - REDIS_HOST=video_harvester_redis



 #volumes:  
   #redis_data:
